### ISSUE TITLE
Cant read `trim_trailing_whitespace` correctly

### ISSUE THREAD

**Issue by mstruebing** [editorconfig/editorconfig-core-go#11]
Hey,

I have something like this code:

```
editorconfig, _ := editorconfig.GetDefinitionForFilename(file)
if strings.HasSuffix(file, "README.md") {
	fmt.Println(editorconfig)
	fmt.Println(editorconfig.TrimTrailingWhitespace)
}
```

The output is:

```
&{ utf-8 space 4 4 lf true true map[charset:utf-8 trim_trailing_whitespace:false insert_final_newline:true indent_style:space indent_size:4 end_of_line:lf]}
true
```

I don't get it - the first line let me believe that `trim_trailing_whitespace` is set to false (and it is indeed written like that in my `.editorconfig`) but the second line says that `trim_trailing_whitespace` is set to false.

What do I do wrong?

In case you need the live-code, it can be found here: https://github.com/editorconfig-checker/editorconfig-checker.go/blob/whatsHappening/src/main.go#L206

My `.editorconfig` looks like this:

```
[*]
charset = utf-8
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = space
indent_size = 4
end_of_line = lf

[*.md]
trim_trailing_whitespace = false

[*.go]
indent_style = tab

[Makefile]
indent_style = tab
```

and I'm checking my `README.md` file.

**Comment by mstruebing** [comment]
I've found the issue, I'm able to access it with 'editorconfig.Raw["trim_trailing_whitespace"]`

**Comment by 10sr** [comment]
I think your first code should work, possibly something wrong is happening here...
