### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by mstruebing** [editorconfig/editorconfig-core-go#12]
Hey, I'm using your project right now in one of mine: https://github.com/editorconfig-checker/editorconfig-checker.go

But as I get more and more to a state where I could release an MVP-release I'm asking myself what the status of `editorconfig-core-go` is right now. I would love to cooperate and use the official implementation to retrieve rules for specific files, but as it seems more like a work in progress state I'm not sure if I could take the responsibility to use it in my project especially when you are making changes to this repository later on.

So my concrete question is: is it a readily usable state which needs some minor adjustments or do you plan to do more refactorings, API changes or so on? 
Would you suggest to use it in a 'real-world-program'?

Thanks in advance!

**Comment by andreynering** [comment]
Hi @mstruebing,

I started this but I'm not mostly maintaining it anymore. @10sr has being doing some work, though.

I'd like to point that, IMO, we should not do any breaking changed on version 2. And, for version 3, we should probably migrate to Go modules and move out from the `gopkg.in` import path to `github.com`.

**Comment by 10sr** [comment]
Nice to hear that!

What is needed is to update [this function](https://github.com/editorconfig/editorconfig-core-go/blob/master/editorconfig.go#L125-L163) (and some related lines) so that `ctest` for editorconfig-core-test will finish successfully (you can comment-in [here](https://github.com/editorconfig/editorconfig-core-go/blob/master/Makefile#L24-L25) to run it).
I've already searched for fnmatch libraries implemeneted in golang, but cannot find the one which meets our needs...

**Comment by mstruebing** [comment]
I've compiled a list of the other implementations to gain some inspiration or have a look on how they are doing it

- https://github.com/editorconfig/editorconfig-core-js/blob/master/src/lib/fnmatch.js
- https://github.com/editorconfig/editorconfig-core-net/blob/master/src/EditorConfig.Core/Minimatcher.cs
- https://github.com/editorconfig/editorconfig-core-c/blob/master/src/lib/ec_glob.c
- https://github.com/editorconfig/editorconfig-core-py/blob/master/editorconfig/fnmatch.py
- https://github.com/editorconfig/editorconfig-core-java/blob/a5bb00e622c4e227d0c7e15da0359d3a9922a6c2/src/main/java/org/editorconfig/core/EditorConfig.java#L286
- https://github.com/editorconfig/editorconfig-core-ruby/blob/37ed22333300106bffe217b7334c23fe5ca31235/lib/editor_config.rb#L153

**Comment by dudleycodes** [comment]
Instead of re-implemented the globbing-wheel why not use an existing, high performance library like https://github.com/gobwas/glob?

**Comment by mstruebing** [comment]
I'm not really sure but I think because it didn't do everything like expected in the core tests.
At least, I've tried some libraries and they weren't able to pass all core tests. (I'm not sure I also tested this one)

**Comment by 10sr** [comment]
Sorry forgot to write here, I tried these two libraries and they cannot be used (without modification) for this case...

- github.com/gobwas/glob (https://github.com/editorconfig/editorconfig-core-go/pull/7/commits/a2a3fbb2d7c5f9116d88e8dfbd11357a2709aece)
- github.com/danwakefield/fnmatch (https://github.com/editorconfig/editorconfig-core-go/pull/7/commits/b3d92c7db4ac9b920ab43d32684645ad5e682f57)

**Comment by dudleycodes** [comment]
@10sr - do you mean they need to be modified to work w/ how `editorconfig-core-go` flows or more along the lines of they fail particular test cases that need to be fixed; at which point the can be used?

If it's the later I'll roll up my sleeves and attempt to get those test cases working upstream in one of those projects.

**Comment by 10sr** [comment]
Thanks for your offer! 👍 

These libraries do not pass some glob test cases which editorconfig requires.
For example, both libraries do not pass following (if I remember correctly):

- `match("a{1..3}b", "a2b")` -> true

But please note that, IMO, it is not necessarily a bug that should be fixed.
There are many extensions in glob syntaxes, and it depends on libraries that which syntaxes are supported by these libraries.
So, it is possible that the authors reject accepting new syntaxes like this, even if they are required for editorconfig to work.
This is one of the reasons that I'm going to implement by myself first (another is I do not have enough golang skill to contributing these libraries XP).

So, of couse it is OK to modify and use these libraries, if the authors accept changes for editorconfig!

**Comment by andreynering** [comment]
Closing this since we've been working on this recently, and most of the core tests passes now.

Feel free to still ask questions, though.
