### ISSUE TITLE
Paths with forward slashes don't work in some cases on Windows and Linux

### ISSUE THREAD

**Issue by generalmimon** [editorconfig/editorconfig-core-go#168]
I reported this issue in https://github.com/editorconfig-checker/editorconfig-checker/issues/281 first, but then figured out it's in fact a problem in `editorconfig-core-go` itself that is used by [editorconfig-checker](https://github.com/editorconfig-checker/editorconfig-checker) under the hood.

Please check out https://github.com/editorconfig-checker/editorconfig-checker/issues/281 - I'll repeat some of it here, but not with all the details.

Summary: even though the [EditorConfig spec](https://spec.editorconfig.org/#file-format) declares that forward slashes `/` should always be used as path separators in section headers even on Windows, in reality forward slashes `/` don't work on Windows and only backslashes `\\` do when using `editorconfig-core-go` (contrary to the linked EditorConfig spec).

An example is given in https://github.com/editorconfig-checker/editorconfig-checker/issues/281#issue-1864000959:

**doesn't work** on Windows

```editorconfig
[bin/ksdump]
indent_size = 2
```

**works** on Windows

```editorconfig
[bin\\ksdump]
indent_size = 2
```

Another related problem is that the presence of glob with a forward slash like `bin/ksdump` on Windows actually neutralizes the entire `.editorconfig` section using brace syntax (`{s1,s2,s3}`) where `bin/ksdump` appears, as demonstrated in https://github.com/editorconfig-checker/editorconfig-checker/issues/281#issuecomment-1690645392. This can be observed in slightly changed `editorconfig-core-go` tests too - just change

https://github.com/editorconfig/editorconfig-core-go/blob/0bb51f18a1573bdc43d0e49c2365fc397765b75a/testdata/root/.editorconfig#L1-L5

as follows:

```diff
 root = true
 
-[*.go]
+[{src/a.ini,*.go}]
 indent_style = space
 insert_final_newline = true
```

and run `go test -v ./...` on Windows:

```console
pp@DESKTOP-89OPGF3 MINGW64 /c/temp/editorconfig-core-go (master)
$ go test -v ./...
...

--- FAIL: TestPublicTestDefinitionForFilename (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xb2be66]

goroutine 13 [running]:
testing.tRunner.func1.2({0xb529e0, 0xd1d590})
	C:/Program Files/Go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	C:/Program Files/Go/src/testing/testing.go:1529 +0x39f
panic({0xb529e0, 0xd1d590})
	C:/Program Files/Go/src/runtime/panic.go:884 +0x213
github.com/editorconfig/editorconfig-core-go/v2.TestPublicTestDefinitionForFilename(0x0?)
	C:/temp/editorconfig-core-go/editorconfig_test.go:160 +0xc6
testing.tRunner(0xc000192680, 0xb99210)
	C:/Program Files/Go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	C:/Program Files/Go/src/testing/testing.go:1629 +0x3ea
FAIL	github.com/editorconfig/editorconfig-core-go/v2	0.297s
FAIL
```

If you change `src/a.ini` to `src\\a.ini`, it works (and BTW, I checked that not only the `*.go` glob works, but the `src\\a.ini` is applied too):

```diff
 root = true
 
-[{src/a.ini,*.go}]
+[{src\\a.ini,*.go}]
 indent_style = space
 insert_final_newline = true
```

```console
$ go test -v ./...
...

--- PASS: TestPublicTestDefinitionForFilename (0.00s)
```

---

Weirdly enough, including `src/a.ini` as one of the globs in brace syntax neutralizes the section even on Linux:

```editorconfig
root = true
 
[{src/a.ini,*.go}]
indent_style = space
insert_final_newline = true
```

This is the output from a run in WSL 2:

```console
pp@DESKTOP-89OPGF3:/mnt/c/temp/editorconfig-core-go$ cat testdata/root/.editorconfig
root = true

[{src/a.ini,*.go}]
indent_style = space
insert_final_newline = true
pp@DESKTOP-89OPGF3:/mnt/c/temp/editorconfig-core-go$ make test-go
go test -v ./...
...

--- FAIL: TestPublicTestDefinitionForFilename (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5d4d26]

goroutine 41 [running]:
testing.tRunner.func1.2({0x5fa5e0, 0x7b0350})
        /usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x5fa5e0, 0x7b0350})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/editorconfig/editorconfig-core-go/v2.TestPublicTestDefinitionForFilename(0xc0001196c0?)
        /mnt/c/temp/editorconfig-core-go/editorconfig_test.go:160 +0xc6
testing.tRunner(0xc000119860, 0x63d7a8)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x3ea
FAIL    github.com/editorconfig/editorconfig-core-go/v2 0.029s
FAIL
make: *** [Makefile:17: test-go] Error 1
```

On the other hand, when splitting the brace syntax into two separate sections, both sections work on Linux (whereas on Windows, a path with forward slashes like `src/a.ini` wouldn't work no matter what):

```editorconfig
root = true
 
[src/a.ini]
indent_style = space
insert_final_newline = true

[*.go]
indent_style = space
insert_final_newline = true
```

I haven't dived into the code yet, so the few examples I've presented are all I have for now - hopefully you'll be able to generalize the problem based on them.

**Comment by greut** [comment]
After giving it another try, you're right. When going through the `git ls-files` output, everything is nice and shinny, but not when digging into the files _manually_.

![tl6V1dk](https://github.com/editorconfig/editorconfig-core-go/assets/1388/78530c4f-e372-4be5-afed-f0de233a9e86)

**Comment by generalmimon** [comment]
@greut:

> So, investigation is over :) There is the fix for eclint, https://gitlab.com/greut/eclint/-/merge_requests/146

Sorry, which issue you were actually fixing? I've just installed the latest `eclint` (using `go install gitlab.com/greut/eclint/cmd/eclint@master`, the installed version was `gitlab.com/greut/eclint v0.4.1-0.20230829145804-2c8c3ec817c9`), I created a scrap local Git repo because `eclint` apparently only picks up files tracked by Git and created the following file structure:

```
.
├── .editorconfig
├── .git
│   └── ...
├── foo
│   └── bar
└── subdir
    └── foo
        └── bar.txt
```

The contents of `foo/bar` and `subdir/foo/bar.txt` is the same - they just have a 3-space indent so we have something to test for:

```
$ tail -n +1 foo/bar subdir/foo/bar.txt
==> foo/bar <==
.../ <- 3-space indent
   hello

==> subdir/foo/bar.txt <==
.../ <- 3-space indent
   hello
```

But even with the latest `eclint` version https://gitlab.com/greut/eclint/-/commit/2c8c3ec817c99c06726ece10c0aad85cc094f4ae, I can still reproduce all issues that I mentioned in https://github.com/editorconfig/editorconfig-core-go/issues/168#issue-1868639990. For the following `.editorconfig`:

```editorconfig
root = true

[*]
indent_style = space

[foo/bar]
indent_size = 2

[*.txt]
indent_size = 2
```

(notice the `foo/bar` section; the `*.txt` pattern is just a sanity check that simple patterns work)

clearly the `foo/bar` pattern still doesn't work (only the `*.txt` pattern is applied):

```
C:\temp\editorconfig-core-go-test>eclint -v 5 -add_dir_header
I0829 23:55:55.964665   14400 eclint@v0.4.1-0.20230829145804-2c8c3ec817c9/files.go:32]  "msg"="fallback to `git ls-files`" "dir"="."
I0829 23:55:56.052416   14400 eclint@v0.4.1-0.20230829145804-2c8c3ec817c9/lint.go:98]  "msg"="charset probed" "charset"="" "filename"="foo/bar"
I0829 23:55:56.053267   14400 eclint@v0.4.1-0.20230829145804-2c8c3ec817c9/lint.go:98]  "msg"="charset probed" "charset"="" "filename"="subdir/foo/bar.txt"
subdir/foo/bar.txt:
I0829 23:55:56.056133   14400 eclint@v0.4.1-0.20230829145804-2c8c3ec817c9/print.go:31]  "msg"="lint error" "error"="subdir/foo/bar.txt:2:4: indentation size doesn't match expected 2, got 3"
2:4: indentation size doesn't match expected 2, got 3
            hello

I0829 23:55:56.061663   14400 eclint/main.go:153]  "msg"="some errors were found." "count"=1
```

When I merged the `foo/bar` and `*.txt` sections into one section using brace syntax, the section is still not applied at all, just as I initially described in https://github.com/editorconfig/editorconfig-core-go/issues/168#issue-1868639990:

```editorconfig
root = true

[*]
indent_style = space

[{foo/bar,*.txt}]
indent_size = 2
```

Note: no problems reported by `eclint` this time:

```
C:\temp\editorconfig-core-go-test>eclint -color never -v 5 -add_dir_header
I0830 00:02:39.286417   20052 eclint@v0.4.1-0.20230829145804-2c8c3ec817c9/files.go:32]  "msg"="fallback to `git ls-files`" "dir"="."
I0830 00:02:39.373805   20052 eclint@v0.4.1-0.20230829145804-2c8c3ec817c9/lint.go:98]  "msg"="charset probed" "charset"="" "filename"="foo/bar"
I0830 00:02:39.374115   20052 eclint@v0.4.1-0.20230829145804-2c8c3ec817c9/lint.go:98]  "msg"="charset probed" "charset"="" "filename"="subdir/foo/bar.txt"
```

And again as already explained, if I replace `foo/bar` with `foo\\bar` (which in real cross-platform projects isn't really an option, of course, because that won't work on Unix systems), all things start suddenly working. So from what I can observe, there hasn't been any change in any of the issues I reported.

---

@greut But anyway, **I would like to emphasize** that I strongly believe that _this_ https://github.com/editorconfig/editorconfig-core-go library is the place where to fix the mentioned bugs, not the projects that rely on `editorconfig-core-go` to do its work such as your project https://gitlab.com/greut/eclint or https://github.com/editorconfig-checker/editorconfig-checker.

I don't think you would be even able to work around these `editorconfig-core-go` bugs exclusively by fiddling with https://gitlab.com/greut/eclint (which seems to be your intention so far), other than moving away from `editorconfig-core-go` and reimplementing its functionality directly in https://gitlab.com/greut/eclint (which would be unnecessary work and wouldn't really help anyone, though).

**Comment by generalmimon** [comment]
I'm sure the issues I described are coming directly from `editorconfig-core-go` because I can also just download a binary from https://github.com/editorconfig/editorconfig-core-go/releases/tag/v2.5.2 and reproduce them too, which eliminates the influence of reporting "wrapper" tools like `eclint` or `editorconfig-checker`.

**Comment by greut** [comment]
> But anyway, I would like to emphasize that I strongly believe that this https://github.com/editorconfig/editorconfig-core-go library is the place where to fix the mentioned bugs

@generalmimon PR are welcome mate. There might be more than one issue though. I'm looking forward to reviewing them.

**Comment by generalmimon** [comment]
@greut:

> A starting point might those tests, https://github.com/editorconfig/editorconfig-core-go/blob/master/fnmatch_test.go#L16

Makes sense, perhaps https://github.com/editorconfig/editorconfig-core-test/blob/5ca0b29/glob/braces.in too.

**Comment by greut** [comment]
> sense, perhaps https://github.com/editorconfig/editorconfig-core-test/blob/5ca0b29/glob/braces.in too.

be my guest.
