### ISSUE TITLE
backport and release new version

### ISSUE THREAD

**Issue by carnott-snap** [editorconfig/editorconfig-core-go#27]
The current release that Go modules respect, in the v1 series, is `v1.3.0`, this contains a bug that was fixed in #14. Unfortunately, you also migrated to `/v2/`, thus no module customers on the v1 series can consume this fix. The backport and new release would be appreciated.

**Comment by greut** [comment]
@carnott-snap I don't get the reason to stay away from v2?

**Comment by carnott-snap** [comment]
I would happily upgrade my code, but have some transitive dependencies that are currently using v1, and it is not within my power to make that request.

That being said, it is your decision is you want to continue support for the v1 series, but I would at least ask that a `v1.3.1` tag be made at 0b5e28401ae9. This requires no new code just a tag to finish off the v1 series.

**Comment by greut** [comment]
@carnott-snap would #28 tagged as v1.3.1 be working for you?

**Comment by carnott-snap** [comment]
adding the `go.mod` as well would be optimal, but that should work too.

**Comment by greut** [comment]
@carnott-snap if you're ok with that the PR I could move forward with the 1.x branch.

**Comment by greut** [comment]
v1.3.1 has been pushed.
