### ISSUE TITLE
What does eclint_indent_style do? 

### ISSUE THREAD

**Issue by imcvampire** [editorconfig/editorconfig-core-go#72]
Hi,

Could you share what this line does? https://github.com/editorconfig/editorconfig-core-go/blob/master/.editorconfig#L20

Thank you!

**Comment by greut** [comment]
@imcvampire it's a prefixed value (vendor) for [eclint](https://gitlab.com/greut/eclint#more) which overrides the existing `indent_style` value when running the linter.

Example of prefixed values:
- https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019
- https://blog.jetbrains.com/idea/2019/06/managing-code-style-on-a-directory-level-with-editorconfig/

Cheers
