### ISSUE TITLE
GetDefinitionForFilename fails for windows paths

### ISSUE THREAD

**Issue by tomtomsen** [editorconfig/editorconfig-core-go#88]
**Platform:**
Windows

**Version:**
Tested with current master

**Testcase** 
`.editorconfig`:
```
root = true
[*]
indent_style = tab

[*.ini]
indent_style = space

[test.toml]
indent_style = space
```

`test.ini`
```
[foo]
  bar = "buz"
```

`test.toml`
```
[foo]
  bar = "buz"
```

**Expected behavior**
I expected to get `IndentStyleSpaces` for `test.toml` and `test.ini` with windows paths.
but only `test.ini` returns the expected indent style.

**Unit Test**
```
func TestGetDefinition(t *testing.T) {
       ...

	def, err = ec.GetDefinitionForFilename("C:\\home\\test.toml")
	if err != nil {
		t.Errorf("Couldn't parse file: %v", err)
	}
	assert.Equal(t, IndentStyleSpaces, def.IndentStyle)

	def, err = ec.GetDefinitionForFilename("C:\\home\\test.ini")
	if err != nil {
		t.Errorf("Couldn't parse file: %v", err)
	}
	assert.Equal(t, IndentStyleSpaces, def.IndentStyle)
```

**Problem**
The generated Regular Expression `^(?:/|/.*/)test\.toml$` does not match the path `/C:\\Users\\tom-tomsen\\test.toml`

**Comment by greut** [comment]
Maybe a proper globbing library (e.g. #87) would be more portable.
